apiVersion: v1
kind: Pod
metadata:
  name: ctrreschk-guaranteed
spec:
  restartPolicy: Never
  containers:
  - name: ctrreschk
    image: CI_IMAGE_PLACEHOLDER
    command: ["/ctrreschk", "align"]
    resources:
      requests:
        cpu: "2"
        memory: "64Mi"
      limits:
        cpu: "2"
        memory: "64Mi"
